# Generated by Django 5.0.4 on 2024-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sotck',
            field=models.IntegerField(default=0),
        ),
    ]
