# Generated by Django 5.0.4 on 2024-04-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_sotck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='sotck',
            new_name='stock',
        ),
    ]
